name: Build exercise and solution notebooks

on:
  push:
    branches:
    - main
    paths:
    - 'src/**'

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
    # https://github.com/actions/checkout
    - name: Git checkout latest revision
      uses: actions/checkout@v4

    # https://github.com/actions/setup-python
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Rebuild the final notebooks
      run: |
        python make.py -r

    - name: Commit any change
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add en fr solution-{en,fr}
        ! git diff --cached --quiet && git commit -m "Exercise and solution notebooks rebuilt" && git push
